services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--enable-feature=exemplar-storage'
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    depends_on:
      - frontend
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
      - tempo

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    network_mode: host
    pid: host
    volumes:
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'

  loki:
    image: grafana/loki:3.7.0
    container_name: loki
    restart: unless-stopped
    command:
      - '-config.file=/etc/loki/local-config.yaml'
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml:ro

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    restart: unless-stopped
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    ports:
      - "12345:12345"
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - alloy-data:/var/lib/alloy/data
    depends_on:
      - loki

  tempo:
    image: grafana/tempo:3.0.0
    container_name: tempo
    restart: unless-stopped
    command:
      - '-config.file=/etc/tempo.yaml'
    ports:
      - "3200:3200"
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml:ro

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.158.0
    container_name: otel-collector
    restart: unless-stopped
    command:
      - '--config=/etc/otelcol-contrib/config.yaml'
    volumes:
      - ./otel/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - tempo

  backend:
    build:
      context: ./backend
    container_name: backend-service
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
    depends_on:
      - otel-collector

  frontend:
    build:
      context: ./frontend
    container_name: frontend-service
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
    depends_on:
      - backend
      - otel-collector
  alert-receiver:
    build:
      context: ./alert-receiver
    container_name: alert-receiver
    restart: unless-stopped
    ports:
      - "8081:8081"

volumes:

  # Vamos reaproveitar os dados do Grafana e Prometheus atuais.
  prometheus-data:
    external: true
    name: 02-prometheus_prometheus-data

  grafana-data:
    external: true
    name: 02-prometheus_grafana-data

  alloy-data:
